//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.25 at 02:52:18 PM MEZ 
//


package com.coremedia.util.model.pojo;

import com.coremedia.util.model.helper.StringUtil;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for story complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="story">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="singleTest" type="{}singleTest" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="text" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="iteration" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="comment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "story", propOrder = {
        "content"
})
public class Story {

  @XmlElementRef(name = "singleTest", type = JAXBElement.class)
  @XmlMixed
  protected List<Serializable> content;
  @XmlAttribute(required = true)
  protected String id;
  @XmlAttribute(required = true)
  protected String text;
  @XmlAttribute(required = true)
  protected String iteration;
  @XmlAttribute
  protected String comment;
  @XmlAttribute(required = true)
  protected Testable testable;


  @XmlTransient
  protected List<SingleTest> tests = new ArrayList<SingleTest>();

  @XmlTransient
  protected StoryState state;

  /**
   * Gets the value of the content property.
   * <p/>
   * <p/>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the JAXB object.
   * This is why there is not a <CODE>set</CODE> method for the content property.
   * <p/>
   * <p/>
   * For example, to add a new item, do as follows:
   * <pre>
   *    getContent().add(newItem);
   * </pre>
   * <p/>
   * <p/>
   * <p/>
   * Objects of the following type(s) are allowed in the list
   * {@link String }
   * {@link JAXBElement }{@code <}{@link SingleTest }{@code >}
   */
  public List<Serializable> getContent() {
    if (content == null) {
      content = new ArrayList<Serializable>();
    }
    return this.content;
  }

  /**
   * Gets the value of the id property.
   *
   * @return possible object is
   *         {@link String }
   */
  public String getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setId(String value) {
    this.id = value;
  }

  /**
   * Gets the value of the text property.
   *
   * @return possible object is
   *         {@link String }
   */
  public String getText() {
    return StringUtil.makePrettyHtmlString(text);
  }

  /**
   * Sets the value of the text property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setText(String value) {
    this.text = value;
  }

  /**
   * Gets the value of the iteration property.
   *
   * @return possible object is
   *         {@link String }
   */
  public String getIteration() {
    return iteration;
  }

  /**
   * Sets the value of the iteration property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setIteration(String value) {
    this.iteration = value;
  }

  /**
   * Gets the value of the comment property.
   *
   * @return possible object is
   *         {@link String }
   */
  public String getComment() {
    return StringUtil.makePrettyHtmlString(comment);
  }

  /**
   * Sets the value of the comment property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setComment(String value) {
    this.comment = value;
  }

  public List<SingleTest> getTests() {
    return tests;
  }

  public void setTests(List<SingleTest> tests) {
    this.tests = tests;
  }

  public void addTest(SingleTest test) {
    this.tests.add(test);
  }

  public void setState(StoryState state) {
    this.state = state;
  }

  public StoryState getState() {
    return this.state;
  }

  /**
   * Gets the value of the testable property.
   *
   * @return possible object is
   *         {@link Testable }
   */
  public Testable getTestable() {
    return testable;
  }

  /**
   * Sets the value of the testable property.
   *
   * @param value allowed object is
   *              {@link Testable }
   */
  public void setTestable(Testable value) {
    this.testable = value;
  }

  /**
   * gets SingleTest with handled full name (classname.methodname)
   *
   * @param name
   * @return
   */
  public SingleTest getTestWithName(String name) {
    for (SingleTest test : this.getTests()) {
      if (test.getTestname().equalsIgnoreCase(name)) {
        return test;
      }
    }

    return null;
  }

}
